---
title: "hpo_distribution"
output: html_document
date: "2024-03-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


## path
```{r}
setwd('C:/Users/mchahdil/Desktop/compare_study/') # C:/Users/mchahdil/Desktop/compare_study/ D:/compare_study/
getwd()
path_out ='C:/Users/mchahdil/Desktop/compare_study/output_files/'

```

## libraire

```{r}
library(readxl)
library(ggplot2)
library(reshape2)


```



## open files

 
patient confirmed
```{r}

df_confirmed <- read_excel(paste(path_out,"/df_hpo_solved_confirmed.xlsx", sep='/'))
summary(df_confirmed)
 
```



 patient simulated 
```{r}

df_simulated <- read_excel(paste(path_out,"/df_hpo_simulated.xlsx",sep='/'))
 
# extract two first str in the element of the col 
type_pheno = unique(substr(df_simulated$phenopacket, 1, 2))

# detect if col start with type pheno
# negated 
indice_type = which(grepl(type_pheno[1], df_simulated$phenopacket))
df_simu_negated = df_simulated[indice_type,]

# optimal
indice_type = which(grepl(type_pheno[4], df_simulated$phenopacket))
df_simu_optimal = df_simulated[indice_type,]

# imprecision
indice_type = which(grepl(type_pheno[2], df_simulated$phenopacket))
df_simu_imprecision = df_simulated[indice_type,]

# noisy
indice_type = which(grepl(type_pheno[3], df_simulated$phenopacket))
df_simu_noisy = df_simulated[indice_type,]

```
########################################################################################################################################



## analysis
```{r}

get_high_hpo<- function(col_hpo,text_tittle){
hpo_count = as.factor(col_hpo)
vect_occu = c(summary(hpo_count))

 
df_plot <- data.frame(
  value=vect_occu[1:10] 
  )
 
# how to sort a df but in ggplot not working the data are to sorted
#df_plot_s = df_plot[order(-df_plot$value),,drop=FALSE]


ggplot(df_plot, aes(x=rownames(df_plot), y=value, label = value)) + 
  geom_bar(color="blue",fill = "#84b7f0",stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   geom_text(size = 3, position = position_stack(vjust = 0.5)) +
    ggtitle(paste("Representation of most commons hpo for ",text_tittle,sep = "")) + # for the main title
    xlab("") + # for the x axis label
    ylab("Count")   # for the y axis label

}


 
```





```{r}
get_high_hpo(df_confirmed$hpo,"comfirmed patients")




```



## patient simulated 
```{r}


get_high_hpo(df_simulated$hpo," simulated patients")
get_high_hpo(df_simu_negated$hpo," simulated negated")

get_high_hpo(df_simu_noisy$hpo,"simulated noisy")
get_high_hpo(df_simu_imprecision$hpo,"simulated imprecision")

get_high_hpo(df_simu_optimal$hpo, "simulated optimal")
```


# find the hight hpo in commons
```{r}
count_high_hpo <- function(col_hpo,topn){
  hpo_count = as.factor(col_hpo)
  vect_occu = c(summary(hpo_count))
  
    return (names(vect_occu[1:topn]))  }

```


```{r}


simu_topHPO = count_high_hpo(df_simulated$hpo,10)
conf_topHPO = count_high_hpo(df_confirmed$hpo,10)

simu_N_topHPO = count_high_hpo(df_simu_negated$hpo,10)
simu_Ny_topHPO = count_high_hpo(df_simu_noisy$hpo,10)
simu_I_topHPO = count_high_hpo(df_simu_imprecision$hpo,10)
simu_O_topHPO = count_high_hpo(df_simu_optimal$hpo,10)


       
```


```{r}

# hpo in commons between all simulated and confirmed patients 
compare_comf_simu = intersect(simu_topHPO,conf_topHPO)
compare_comf_simu
```




```{r}

# hpo in commons between comfirmed and optimal
compare_conf_opt = intersect(simu_O_topHPO,conf_topHPO)

compare_conf_opt
```



```{r}

# compare all
compare_all = Reduce(intersect,list(conf_topHPO,simu_topHPO,simu_O_topHPO,simu_N_topHPO,simu_Ny_topHPO,simu_I_topHPO))
compare_all
```



```{r}

# compare all without negated 
compare_exclude_negated = Reduce(intersect,list(conf_topHPO,simu_topHPO,simu_O_topHPO,simu_Ny_topHPO,simu_I_topHPO))
compare_exclude_negated

```



## study the finess of HPO (how deep the hpo are in the ontology) 
```{r}
library(ontologyIndex)
library(ontologySimilarity)

# Load hpo
data(hpo)
hpo_table = as.data.frame(hpo)

```

```{r}

 
get_ancestor_descendant_high_hpo <- function(compare_list,title_hpo){
  count_descendant = c()
  count_ancestor = c()
  
  for (i in 1:(length(compare_list)) ) {
    #print(compare_list[i])
    #print(paste("descendant",length(get_descendants(hpo, compare_list[i])) ))
    #print(paste("ancestor",length(get_ancestors(hpo, compare_list[i])) ))
   
    count_descendant[i] = length(get_descendants(hpo, compare_list[i]))
    count_ancestor[i] = length(get_ancestors(hpo, compare_list[i])) 
  
  }
  
  # add two list simulately
  count_descendant_ancestor = c(rbind(count_descendant,count_ancestor))
  
  # replicate each element by b in a vector
  a<-compare_list
  b<-2  
  a<-sapply(a, function (x) rep(x,b))
  compare_list_replicate<-as.vector(a)
  
  
  df_plot <- data.frame(hpo_name = compare_list_replicate,
                   value = count_descendant_ancestor,
                   condition  = rep(c("descendants","ancestor" ) , length(compare_list))
                    )
  
  ggplot(df_plot, aes(fill=condition, y=count_descendant_ancestor, x=hpo_name)) + 
      geom_bar(position="dodge", stat="identity") +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
      ggtitle(paste("Ancestor/descendant of most commons hpo between ",title_hpo,sep = "")) +  
      xlab("") +
      ylab("Count")  
    
}


```


```{r}
get_ancestor_descendant_high_hpo(compare_exclude_negated,"all excluded negated ")


```


```{r}
get_ancestor_descendant_high_hpo(compare_conf_opt,"comfirmed and optimal ")

```


```{r}
get_ancestor_descendant_high_hpo(compare_comf_simu,"comfirmed and simulated ")

```
hpo qui revient le plus souvent est HP:750
